---
title: "Introduction to Econometrics with R"
author: "M. Arnold, M. Schmelzer, A. Gerber"
date: "20 Mai 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Chapter 3
## Section 3.5

### Table 3.1
In order to reproduce table 3.1 you need to download the data from the books source (LINK).
We simply read in the data and then make use of the powerful package dplyr to subset the data.

```{r, echo=T}
library(dplyr, quietly=T)
# Read in CPS data (taken from http:// ....)
cps_dat <- read.csv("data/cps_ch3.csv", sep=";", dec=".")
# Get an overview of the data structure
head(cps_dat)
# Take cps_dat %>% group data by gender and year %>% compute the mean, standard deviation
# and number of observations for each group
avgs <- cps_dat %>% group_by(a_sex, year) %>% summarise(mean(ahe12), sd(ahe12), n())
# Round all results and print them
round(avgs, 2)
```

## Chapter 4

```{r Table 4.1}
library(AER)                                                    # contains the dataset 
data(CASchools) 

CASchools$tsratio  <- CASchools$students/CASchools$teachers     # teacher-student-ratio
CASchools$score    <- (CASchools$read + CASchools$math)/2       # average test-score

mean(CASchools$tsratio) 
mean(CASchools$score)
sd(CASchools$tsratio) 
sd(CASchools$score)
quantiles          <- c(0.10, 0.25, 0.4, 0.5, 0.6, 0.75, 0.9)
quantile(CASchools$tsratio, quantiles)
quantile(CASchools$score, quantiles)

```




```{r Figure 4.2}
plot(score ~ tsratio, 
     data = CASchools,
     main = "Scatterplot of Test Score vs. Student-Teacher Ratio", 
     xlab = "Student teacher-ratio (X)",
     ylab = "Test Score (Y)",
     xlim = c(10,30),
     ylim = c(600, 720))
```

```{r}
attach(CASchools)
beta_1 <- sum((tsratio - mean(tsratio))*(score - mean(score))) / sum((tsratio - mean(tsratio))^2)
beta_0 <- mean(score) - beta_1 * mean(tsratio)
```

```{r}
library(xtable)
plot(score ~ tsratio, 
     data = CASchools,
     main = "Scatterplot of Test Score vs. Student-Teacher Ratio", 
     xlab = "Student teacher-ratio (X)",
     ylab = "Test Score (Y)",
     xlim = c(10,30),
     ylim = c(600, 720))

linear_model <- lm(score ~ tsratio, data = CASchools)
linear_model

abline(a = beta_0, b = beta_1)
```


```{r}
linear_model <- lm(score ~ tsratio, data = CASchools)
linear_model
```

```{r Figure 4.3}
library(xtable)
plot(score ~ tsratio, 
     data = CASchools,
     main = "Scatterplot of Test Score vs. Student-Teacher Ratio", 
     xlab = "Student teacher-ratio (X)",
     ylab = "Test Score (Y)",
     xlim = c(10,30),
     ylim = c(600, 720))

abline(linear_model)
```


Was ist hier looos???

Klötenkasper1337

Wie jetzt gehts endlich?


Test test test



dfkhdlfhd

ppp

